### ISSUE TITLE
Couple of issues with new release

### ISSUE THREAD

**Issue by elvisish** [dalexeev/gdscript-preprocessor#3]
I tried the latest version and I'm having a couple of errors:
![image](https://github.com/dalexeev/gdscript-preprocessor/assets/16231628/942be7a9-0246-437a-8f01-3e5aac8af899)
![image](https://github.com/dalexeev/gdscript-preprocessor/assets/16231628/2910dfb2-475b-45ea-943e-a48c7cbb96d1)

**Comment by dalexeev** [comment]
The plugin has been updated to Godot 4.2 and is now incompatible with earlier versions.

**Comment by dalexeev** [comment]
Resolved by fa1661b2e717bbb3ebfa9582482fb963476fd11e.

I've backported the plugin to Godot 4.1 (see [4.1](https://github.com/dalexeev/gdscript-preprocessor/tree/4.1) branch).
