### ISSUE TITLE
Code is exported in both pre-processed and original version.

### ISSUE THREAD

**Issue by Pshy0** [dalexeev/gdscript-preprocessor#4]
Plugin version: 1.1-dev
Godot version: 4.2.2.rc1

When exporting the project, editing the exported binary shows that the scripts are exported in both their preprocessed and original version.

![image](https://github.com/dalexeev/gdscript-preprocessor/assets/44928041/52dabf96-2701-497d-96b9-45dd2fb9f04d)

**Comment by Pshy0** [comment]
Maybe you are not remapping the file you export, and maybe you also need to use `skip()`.

**Comment by dalexeev** [comment]
Thank you for this valuable issue! I assumed that PCK cannot have two files with the same path and that the contents of the PCK are equivalent to ZIP. So I didn't call `skip()`, figuring Godot would just replace the file or at least report an error (we should report this to the Godot repo).

Unfortunately, remaps do not work well with GDScript (global names and `preload`). I'll try adding `skip()`.

**Comment by Pshy0** [comment]
Actually this is what I see when exporting to zip:
![image](https://github.com/dalexeev/gdscript-preprocessor/assets/44928041/1afd4d03-6e18-4224-a36a-1ec2f1edc496)
Perhaps your zip explorer program does not show when a zip contains two files with the same file name?

**Comment by Pshy0** [comment]
I didnt know it was possible btw, and apparently my computer neither, I can only open the later...

**Comment by Pshy0** [comment]
> Unfortunately, remaps do not work well with GDScript (global names and preload). I'll try adding skip().

I think it will be fine if you remap (using `add_file`) to the same path and then skip the currently being exported script, it works in my plugin.

**Comment by dalexeev** [comment]
Fixed in 461016c29c418713028e797822ab04b83d51fa50. Thanks for testing! Please let me know if you find any new issues.
