### ISSUE TITLE
Strip `@tool` away from pre-processed sources.

### ISSUE THREAD

**Issue by Pshy0** [dalexeev/gdscript-preprocessor#6]
Since you simplify `Engine.is_editor_hint()` calls, you can also get rid of `@tool`.

**Comment by dalexeev** [comment]
It is already configurable, but we can make this the default behavior.

https://github.com/dalexeev/gdscript-preprocessor/blob/abe1993e2d8db9a3c6a67c1678366491adcbe4f6/addons/gdscript_preprocessor/export_plugin.gd#L28

**Comment by dalexeev** [comment]
Implemented in 461016c29c418713028e797822ab04b83d51fa50. Thanks for the suggestion!
